openapi: 3.0.0
info:
  title: using JWToken, APIcache and rate limiting with RESTAPI
  description: MongoDB ExpressJS NodeJS REST API
  version: 1.0.0
servers:
  - url: https://test-blog.up.railway.app/
    description: Localhost development server
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    Post:
      type: object
      properties:
        title:
          type: string
        body:
          type: string


    Comment:
      type: object
      properties:
        body:
          type: string

paths:
  /signup:
    post:
      summary: Register a new User
      description: Register a new User in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: User created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string


  /login:
    post:
      summary: Login a User
      description: Login a User in order to get JWT token (auth-token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      
      responses:
        200:
          description: User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string


  /dashboard:
    get:
      security:
        - bearerAuth: []
      summary: Dashboard of the user
      description: Get details of login user
      responses:
        200:
          description: The details of the login user
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:  
                    type: string


  /api/users:
    get:
      security:
        - bearerAuth: []
      summary: Retrieves a list of registered users
      description: Retrieves a list of users as JSON objects.
      responses:
        200:
          description: A list of users JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"


  /api/user/{id}:
    get:
      security:
        - bearerAuth: []
      summary: Retrieves a Specific User
      description: Retrieves a specific User based on it's id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A User in the format of a JSON object.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/User"

  /api/post:
    post:
      security:
        - bearerAuth: []
      summary: Create a new Post
      description: Create a new Post      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        201:
          description: Post created succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

  /api/post/{id}/comment:
    post:
      security:
        - bearerAuth: []
      summary: Creates a new comment on a specific post
      description: Creates a new comment on a post based on it's id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comment"

      responses:
        201:
          description: A Comment in the format of a JSON object.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Comment"

  /api/posts:
    get:
      security:
        - bearerAuth: []
      summary: Retrieves all Posts and Comments of the logged in user.
      description: Retrieves a logged in user Posts and comments if there is any available.
      responses:
        200:
          description: A list of Posts in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"

  /api/post/{id}:
    get:
      security:
        - bearerAuth: []
      summary: Retrieves a Specific Post and Comment
      description: Retrieves a specific Post based on it's id and it's comments.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A Post in the format of a JSON object.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Post"


    put:
      security:
        - bearerAuth: []
      summary: Updates a specific Post
      description: Updates a specific Post based on it id      
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"

      responses:
        201:
          description: Post updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"


    delete:
      security:
        - bearerAuth: []
      summary: Deletes a specific Post 
      description: Deletes a specific Post based on it's id            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string      

      responses:
        201:
          description: Post deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"